### ISSUE TITLE
你好，请问一下你用的是哪个版本得android studio，为什么我调试不出来呢，求回答，谢谢

### ISSUE THREAD

**Issue by littlegirl-ops** [yanxiaonuo/MusicPlayer_XiangDa#2]

**Comment by yanxiaonuo** [comment]
我刚刚测试了下，我目前用的版本为3.5.2没问题，你看下你那边是不是网络问题导致？

**Comment by yanxiaonuo** [comment]
> _没有提供描述。_

我刚刚测试了下，我目前用的版本为3.5.2没问题，你看下你那边是不是网络问题导致？
![image](https://user-images.githubusercontent.com/33899039/78325624-bb91b500-75aa-11ea-8d15-60033edbf7c7.png)

**Comment by littlegirl-ops** [comment]
好的，我重新下载一个试试，谢谢你的回答



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yanxiaonuo <notifications@github.com&gt;
发送时间: 2020年4月3日 12:58
收件人: yanxiaonuo/MusicPlayer_XiangDa <MusicPlayer_XiangDa@noreply.github.com&gt;
抄送: littlegirl-ops <979206649@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yanxiaonuo/MusicPlayer_XiangDa] 你好，请问一下你用的是哪个版本得android studio，为什么我调试不出来呢，求回答，谢谢 (#2)





  
没有提供描述。
  
我刚刚测试了下，我目前用的版本为3.5.2没问题，你看下你那边是不是网络问题导致？

**Comment by littlegirl-ops** [comment]
您好，冒昧打扰了，我上次请教了程序运行的问题，我是一名大学生，在做毕业设计，题目是具有语音识别的音乐播放器，在加语音识别功能遇到问题，您是否有时间帮我加一个语音识别功能，有偿求助。再次抱歉打扰到您！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yanxiaonuo <notifications@github.com&gt;
发送时间: 2020年4月3日 12:58
收件人: yanxiaonuo/MusicPlayer_XiangDa <MusicPlayer_XiangDa@noreply.github.com&gt;
抄送: littlegirl-ops <979206649@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yanxiaonuo/MusicPlayer_XiangDa] 你好，请问一下你用的是哪个版本得android studio，为什么我调试不出来呢，求回答，谢谢 (#2)





  
没有提供描述。
  
我刚刚测试了下，我目前用的版本为3.5.2没问题，你看下你那边是不是网络问题导致？

**Comment by yanxiaonuo** [comment]
我最近时间比较紧，你直接去科大讯飞开放平台集成就OK，有示例APP，以及视频教学。
语音听写 Android SDK 文档
https://www.xfyun.cn/doc/asr/voicedictation/Android-SDK.html#_1%E3%80%81%E7%AE%80%E4%BB%8B

集成视频
https://www.aidaxue.com/course/courseDetail?id=233

**Comment by littlegirl-ops** [comment]
好的，非常感谢你的指导！





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: yanxiaonuo <notifications@github.com&gt;
发送时间: 2020年4月9日 13:40
收件人: yanxiaonuo/MusicPlayer_XiangDa <MusicPlayer_XiangDa@noreply.github.com&gt;
抄送: littlegirl-ops <979206649@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yanxiaonuo/MusicPlayer_XiangDa] 你好，请问一下你用的是哪个版本得android studio，为什么我调试不出来呢，求回答，谢谢 (#2)





 
我最近时间比较紧，你直接去科大讯飞开放平台集成就OK，有示例APP，以及视频教学。
 语音听写 Android SDK 文档
 https://www.xfyun.cn/doc/asr/voicedictation/Android-SDK.html#_1%E3%80%81%E7%AE%80%E4%BB%8B
 
集成视频
 https://www.aidaxue.com/course/courseDetail?id=233
